### ISSUE TITLE
Model state after table_delete()

### ISSUE THREAD

**Issue by mikecee** [jlafon/PynamoDB#165]
Deleting and then immediately trying to (re)creating a table for a particular Model i.e.

``` python
    CLS.delete_table()
    CLS.create_table(wait=true)
```

results in a stacktrace and error that the table doesn't exist(!!):

``` python
Traceback (most recent call last):
  File "mre2.py", line 36, in <module>
    JavaScriptTears.create_table(wait=True)
  File "/foo/venv/lib/python2.7/site-packages/pynamodb/models.py", line 720, in create_table
    status = cls._get_connection().describe_table()
  File "/foo/venv/lib/python2.7/site-packages/pynamodb/connection/table.py", line 181, in describe_table
    return self.connection.describe_table(self.table_name)
  File "/foo/venv/lib/python2.7/site-packages/pynamodb/connection/base.py", line 553, in describe_table
    tbl = self.get_meta_table(table_name, refresh=True)
  File "/foo/venv/lib/python2.7/site-packages/pynamodb/connection/base.py", line 405, in get_meta_table
    raise TableDoesNotExist(e.response['Error']['Message'])
pynamodb.exceptions.TableDoesNotExist: Table does not exist: `Requested resource not found: Table: table-one not found` 
```

Code to reproduce on Python 2.7.12 and PynamoDB 1.5.3 (with an ugly, temporary, non-patch workaround commented out):

```python
#!/usr/bin/env python2.7

from pynamodb.models import Model
from pynamodb.attributes import UnicodeAttribute, NumberAttribute

class JavaScriptTears(Model):

    class Meta:
        table_name='table-one'
        region     = 'us-west-2'
        read_capacity_units = 1
        write_capacity_units = 1

    framework = UnicodeAttribute(hash_key=True)
    version = NumberAttribute(range_key=True)


if __name__ == '__main__':

    # Make if not present
    if not JavaScriptTears.exists():
        print "1. Creating table"
        JavaScriptTears.create_table(wait=True)
    else:
        print "1. Table already exists"

    # Remove it
    print "2. Deleting table"
    JavaScriptTears.delete_table()

    ## Workaround; Force reconnection. Uncomment below
    # JavaScriptTears._connection = None
    # JavaScriptTears._get_connection()

    print "3. Recreating table"
    JavaScriptTears.create_table(wait=True)
```

**Comment by Drewrockon** [comment]
Also seeing this issue in 4.0.0 python 3.7

Is there a workaround for this? Deleting a table and recreating it is supposed to be cheaper than deleting every record in the table

**Comment by ikonst** [comment]
I actually found the opposite to be true (assuming that you're doing it in tests) 🙄

Could it be that "reconnecting" simply introduces the necessary delay? What happens when you simply sleep?

**Comment by Drewrockon** [comment]
It seems like the wait logic in create_table is the problem. It calls describe table but doesn't catch TableDoesNotExist which is an error you would expect if you are waiting for a table to be created

**Comment by ikonst** [comment]
Uh, you might be right. FWIW I think @jpinner-lyft wanted to remove the `describe_table` call completely (though, then it's unclear to me _how_ one waits on a table's creation).

**Comment by Drewrockon** [comment]
Interesting, I mean if you can figure out a way then sure cut that part out...

I tried setting wait=False and just waiting myself... It seems like the table just never gets created at all no matter how long I wait... Is it possible an exception is getting eaten somewhere?

**Comment by Drewrockon** [comment]
Ok... I think you understood the issue before I did. The wait function isn't the problem... it is that there is no wait function in delete table so the `if cls.exists()` check in create_table means we never even try to create the table and that results in the wait function failing.

This is the solution I am using:
```@staticmethod
    def _flush_table(model_class: Model) -> None:
        """
        Delete and recreate the table to flush all records
        :param model_class: The Model for the table to flush
        :return: None
        """
        try:
            model_class.delete_table()
        except TableError:
            pass
        # Wait for table to delete
        while True:
            if model_class.exists():
                sleep(2)
            else:
                break
        model_class.create_table(wait=True, billing_mode=PAY_PER_REQUEST_BILLING_MODE)```

So I guess a feature request for https://github.com/pynamodb/PynamoDB/issues/519 is what is really needed
