### ISSUE TITLE
Rate limited scans and Throttle do not work with GSIs

### ISSUE THREAD

**Issue by brandond** [jlafon/PynamoDB#239]
When GSIs are used, the consumed capacity value returned by DynamoDB is a dict instead of a float. This breaks both rate_limited_scan and the experimental Throttle interface, since they don't handle this properly:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ec2-user/ansible-env/lib/python2.7/site-packages/pynamodb/models.py", line 707, in rate_limited_scan
    for item in scan_result:
  File "/home/ec2-user/ansible-env/lib/python2.7/site-packages/pynamodb/connection/base.py", line 1052, in rate_limited_scan
    total_consumed_read_capacity += latest_scan_consumed_capacity
TypeError: unsupported operand type(s) for +=: 'float' and 'dict'
```

**Comment by brandond** [comment]
NM, this appears to be fixed by #235, will test.
